### ISSUE TITLE
[quesiton] My /etc/searx/settings.yml setup

### ISSUE THREAD

**Issue by return42** [return42/searx-next#7]
To share user experience I want to leave my actual `/etc/searx/settings.yml` setup here. 

My searx setup has a weight on 

- safe-search
- german-speaking user base 
  - pure EN engines in categories 'general' and 'news' are disabled by default
  - german-speaking content like the one from mediathekviewweb are placed in category 'general'

```yml
use_default_settings: True

general:
    debug : False
    instance_name : "searx@darmarIT"

search:
    safe_search : 2
    autocomplete : "duckduckgo"
    default_lang : ""

server:
    port : 8888
    bind_address : "127.0.0.1" 
    secret_key : "xxxxxxxxxxxxxxx"
    base_url: https://darmarit.org/searx
    image_proxy : False

result_proxy:
    url : http://127.0.0.1:3000/
    key : !!binary "xxxxxxxxxxxxxxxxxxxxxxxxxx"

engines:

  - name : mediathekviewweb
    engine : mediathekviewweb
    shortcut : mvw
    categories : general

  - name : springer nature
    api_key : "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
    disabled : False

# core.ac response very slow (inital most often 10sec.)

  - name : core.ac.uk
    api_key : "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
    timeout : 6

# duden has very often HTTP errors

  - name : duden
    disabled : True

  - name : duckduckgo
    disabled : False

# yahoo news are only english

  - name : yahoo news
    disabled: True

# yahoo language support does not work

  - name : yahoo
    disabled : False

# reddit does not support languages

  - name : reddit
    timeout : 3
    disabled : True

  - name : fdroid
    disabled : False

  - name: apk mirror
    disabled: False

# bing is broken

  - name : bing
    disabled: True
```
